#!/bin/bash
wall $'    #Architecture: '`uname -a` \
$'\n    #CPU physical: '` grep -c processor /proc/cpuinfo` \
$'\n    #vCPU: '` grep -c processor /proc/cpuinfo` \
$'\n    '`free -m | awk 'NR==2{printf "#Memory Usage: %s/%sMB (%.2f%%)", $3,$2,$3*100/$2 }'` \
$'\n    '`df -h | awk 'NR==4{printf "#Disk Usage: %d/%dGB (%s)", $3,$2,$5}'` \
$'\n    '`top -bn1 | grep load | awk '{printf "#CPU Load: %.2f%%\n", $(NF-2)}'` \
$'\n    '`who -b | awk '{printf "#Last boot: %s %s", $3,$4}'` \
$'\n    #LVM use:' `lsblk | grep lvm | awk '{if ($1) {print "yes";exit;} else {print "no"} }'` \
$'\n    #Connections TCP: '`ss | grep tcp | wc -l ` ESTABLISHED \
$'\n    #User log: '`who | cut -d " " -f 1 | sort -u | wc -l`\
$'\n    #Network: IP '`hostname -I``cat /sys/class/net/*/address | awk 'NR==1{printf "(%s)", $1}'` \
$'\n    #Sudo: '`cat .bash_history | grep sudo | wc -l ` cmd \